activity_id: 13

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    n_estimators: 100
    max_depth: 9
    learning_rate: 0.9447765407999094
    num_leaves: 393
    min_child_samples: 56
    lambda_l1: 92.60868231060914
    lambda_l2: 231.2068710418916
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 1.9448297874881904
    max_depth: 10
    min_child_weights: 2
    subsample: 0.8102593242492765
    gamma: 0.10774874174627591
    lambda: 0.5251934897985038
    alpha: 0.9395158201142929