activity_id: 11

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    n_estimators: 100
    max_depth: 9
    learning_rate: 0.6702193143358078
    num_leaves: 355
    min_child_samples: 54
    lambda_l1: 22.19544354881218
    lambda_l2: 133.27633027433654
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 0.8449403673267283
    max_depth: 5
    min_child_weights: 5
    subsample: 0.5526926384904539
    gamma: 1.5475782401500253
    lambda: 0.38388899273074356
    alpha: 0.6426222132043027