activity_id: 2

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    seed: 0
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.924
    num_leaves: 47
    min_child_samples: 57
    lambda_l1: 77.182
    lambda_l2: 247.589
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 0.9413183608902439
    max_depth: 7
    min_child_weights: 1
    subsample: 0.7454417707113266
    gamma: 9.0759752360
    lambda: 0.44652217357613
    alpha: 0.46441857058
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 320
    max_depth: 18
    min_samples_split: 4
    max_features: 0.505