activity_id: 8

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    n_estimators: 100
    max_depth: 9
    learning_rate: 0.27830478929189845
    num_leaves: 63
    min_child_samples: 42
    lambda_l1: 13.97011229324224
    lambda_l2: 103.72499367275658
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 0.5888518753760856
    max_depth: 4
    min_child_weights: 0
    subsample: 0.916309922773969
    gamma: 7.781567509498505
    lambda: 0.8700121482468192
    alpha: 0.9786183422327