activity_id: 4

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.5094314894970887
    num_leaves: 18
    min_child_samples: 54
    lambda_l1: 50.111869058783626
    lambda_l2: 213.6886769107986
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 0.7480131458460781
    max_depth: 9
    min_child_weights: 3
    subsample: 0.5004476896525016
    gamma: 6.14526557195308
    lambda: 0.8841524104111551
    alpha: 0.8834891256292106
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 138
    max_depth: 5
    min_samples_split: 5
    max_features: 0.826