activity_id: 10

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.6722265126917167
    num_leaves: 2
    min_child_samples: 44
    lambda_l1: 5.32362396290027
    lambda_l2: 210.9285457524455
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 1
    max_depth: 10
    min_child_weights: 7
    subsample: 0.8625835176000274
    gamma: 4.745755879156528
    lambda: 0.5072683482500008
    alpha: 0.4439614863252417