activity_id: 3

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    seed: 0
    n_estimators: 100
    max_depth: 10
    learning_rate: 0.449
    num_leaves: 464
    min_child_samples: 46
    lambda_l1: 3.161
    lambda_l2: 185.635