activity_id: 1

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    seed: 0
    n_estimators: 100
    max_depth: 10
    learning_rate: 0.547
    num_leaves: 876
    min_child_samples: 43
    lambda_l1: 16.315
    lambda_l2: 236.385
xgb:
  params:
    objective: 'multi:softprob'
    eval_metric: 'mlogloss'
    num_class: 4
    seed: 0
    nthread: 20
    max_depth: 7
    learning_rate: 0.02
    min_child_weight: 1
    subsample: 0.75
    colsample_bytree: 0.7
    reg_alpha: 0.1


