activity_id: 9

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    n_estimators: 100
    max_depth: 9
    learning_rate: 0.2713645399017636
    num_leaves: 353
    min_child_samples: 37
    lambda_l1: 48.62201618983212
    lambda_l2: 235.7138263643347
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 0.5071734060549825
    max_depth: 4
    min_child_weights: 1
    subsample: 0.5330971569828159
    gamma: 7.5945163121264265
    lambda: 0.8624602936684614
    alpha: 0.799761266784069