defaults:
  - classifier: mlp_8 # 引用模型参数配置文件
  - _self_

dataset:
  default:
    back_to_root: "../.."
    data_path: "output/feature_selection"
    fold_groups_path: "input/feature_extraction"
    fold_groups_name:  "fold_groups_new_with_combinations.csv"
    severity_mapping: {0: 0, 1: 1, 2: 2, 3: 3}

optuna:
  n_trials: 172
  timeout: 600  # 超参数优化的超时时间（秒）
  direction: "maximize"
  storage: "sqlite:///optuna.db"

seed: 0
expname: "${now:%Y%m%d%H%M%S}"
