activity_id: 16

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    max_depth: 8
    learning_rate: 0.637438073843044
    num_leaves: 243
    min_child_samples: 60
    lambda_l1: 59.96497281768776
    lambda_l2: 113.10405050800624
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 1.9448297874881904
    max_depth: 10
    min_child_weights: 2
    subsample: 0.8102593242492765
    gamma: 0.10774874174627591
    lambda: 0.5251934897985038
    alpha: 0.9395158201142929
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 499
    max_depth: 7
    min_samples_split: 4
    max_features: 0.52
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.020408299422266973
    learning_rate_init: 0.000058254105181128
    max_iter: 427
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.0000369086713560466
    learning_rate_init: 0.00007
    max_iter: 958
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha:  0.09256
    learning_rate_init: 0.02987
    max_iter: 608
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 80
    C: 87.13
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 80
    C: 87.13
svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009