activity_id: 5

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    seed: 0
    max_depth: 9
    learning_rate: 0.758052112327382
    num_leaves: 510
    min_child_samples: 45
    lambda_l1: 9.19450884620122
    lambda_l2: 159.28310490740608
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta:  0.5584213563298879
    max_depth: 4
    min_child_weights: 3
    subsample: 0.9476829561124702
    gamma: 9.035877630799067
    lambda: 0.9614511315170102
    alpha: 0.7982840969371214
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 300
    max_depth: 10
    min_samples_split: 2
    max_features: 0.52
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.0003086473425042113
    learning_rate_init: 0.007800985882120463
    max_iter: 992
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.004570429012062801
    learning_rate_init: 0.007662710706532892
    max_iter: 384
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.00187
    learning_rate_init: 0.00218
    max_iter: 671
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 18
    C: 815.66
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 18
    C: 815.66
svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009